package model.service;

import model.view.XxTnaDatesVOImpl;
import model.view.XxTnaDefaultBuyerWiseVOImpl;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jul 01 09:34:51 BDT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for XxTnaDatesVO1.
     * @return XxTnaDatesVO1
     */
    public XxTnaDatesVOImpl getXxTnaDatesVO1() {
        return (XxTnaDatesVOImpl)findViewObject("XxTnaDatesVO1");
    }

    /**
     * Container's getter for XxTnaFabricOriginVO1.
     * @return XxTnaFabricOriginVO1
     */
    public ViewObjectImpl getXxTnaFabricOriginVO1() {
        return (ViewObjectImpl)findViewObject("XxTnaFabricOriginVO1");
    }

    /**
     * Container's getter for BuyerVO1.
     * @return BuyerVO1
     */
    public ViewObjectImpl getBuyerVO1() {
        return (ViewObjectImpl)findViewObject("BuyerVO1");
    }

    /**
     * Container's getter for XxTnaDefaultBuyerWiseVO1.
     * @return XxTnaDefaultBuyerWiseVO1
     */
    public XxTnaDefaultBuyerWiseVOImpl getXxTnaDefaultBuyerWiseVO1() {
        return (XxTnaDefaultBuyerWiseVOImpl)findViewObject("XxTnaDefaultBuyerWiseVO1");
    }

    /**
     * Container's getter for XxTnaHVO1.
     * @return XxTnaHVO1
     */
    public ViewObjectImpl getXxTnaHVO1() {
        return (ViewObjectImpl)findViewObject("XxTnaHVO1");
    }

    /**
     * Container's getter for PocStyleWashFabricVO1.
     * @return PocStyleWashFabricVO1
     */
    public ViewObjectImpl getPocStyleWashFabricVO1() {
        return (ViewObjectImpl)findViewObject("PocStyleWashFabricVO1");
    }

    /**
     * Container's getter for BuyerVO_vs_XxTnaDefaultBuyerWiseVO_VL1.
     * @return BuyerVO_vs_XxTnaDefaultBuyerWiseVO_VL1
     */
    public ViewLinkImpl getBuyerVO_vs_XxTnaDefaultBuyerWiseVO_VL1() {
        return (ViewLinkImpl)findViewLink("BuyerVO_vs_XxTnaDefaultBuyerWiseVO_VL1");
    }
}
