package model.entity;

import java.sql.SQLException;

import java.util.Map;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jun 23 17:32:08 BDT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxTnaDatesEOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        TnaDateId {
            public Object get(XxTnaDatesEOImpl obj) {
                return obj.getTnaDateId();
            }

            public void put(XxTnaDatesEOImpl obj, Object value) {
                obj.setTnaDateId((Number)value);
            }
        }
        ,
        TnaDateName {
            public Object get(XxTnaDatesEOImpl obj) {
                return obj.getTnaDateName();
            }

            public void put(XxTnaDatesEOImpl obj, Object value) {
                obj.setTnaDateName((String)value);
            }
        }
        ,
        XxTnaDefaultBuyerWiseEO {
            public Object get(XxTnaDatesEOImpl obj) {
                return obj.getXxTnaDefaultBuyerWiseEO();
            }

            public void put(XxTnaDatesEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(XxTnaDatesEOImpl object);

        public abstract void put(XxTnaDatesEOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int TNADATEID = AttributesEnum.TnaDateId.index();
    public static final int TNADATENAME = AttributesEnum.TnaDateName.index();
    public static final int XXTNADEFAULTBUYERWISEEO = AttributesEnum.XxTnaDefaultBuyerWiseEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxTnaDatesEOImpl() {
    }

    /**
     * Gets the attribute value for TnaDateId, using the alias name TnaDateId.
     * @return the TnaDateId
     */
    public Number getTnaDateId() {
        return (Number)getAttributeInternal(TNADATEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for TnaDateId.
     * @param value value to set the TnaDateId
     */
    public void setTnaDateId(Number value) {
        setAttributeInternal(TNADATEID, value);
    }

    /**
     * Gets the attribute value for TnaDateName, using the alias name TnaDateName.
     * @return the TnaDateName
     */
    public String getTnaDateName() {
        return (String)getAttributeInternal(TNADATENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for TnaDateName.
     * @param value value to set the TnaDateName
     */
    public void setTnaDateName(String value) {
        setAttributeInternal(TNADATENAME, value.trim());
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getXxTnaDefaultBuyerWiseEO() {
        return (RowIterator)getAttributeInternal(XXTNADEFAULTBUYERWISEEO);
    }

    /**
     * @param tnaDateId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number tnaDateId) {
        return new Key(new Object[]{tnaDateId});
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("model.entity.XxTnaDatesEO");
        }
        return mDefinitionObject;
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        ;
        
        super.create(attributeList);
        
         oracle.jbo.server.SequenceImpl s =
         new oracle.jbo.server.SequenceImpl("XX_TNA_DATES_S",  getDBTransaction());
        oracle.jbo.domain.Number sVal = s.getSequenceNumber();
         this.setTnaDateId(sVal);
                  
     
        
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}
